### ISSUE TITLE
Time Elapsed Widget

### ISSUE THREAD

**Issue by schaufma** [Pe8er/Sidebar.Widget#6]
hi there...

the widget only shows "Sidebar.widget/Time Elapsed" ... is there something to config or an manual? what i´m doing wrong?

perhaps a language problem (german mac os x)?

thanks in advance ...

markus

**Comment by Pe8er** [comment]
It could be related to language, yes. If you open `Time Elapsed.widget/Time Elapsed.applescript`, you will see in line 3:

`set quitDate to date "Monday, October 29, 2012 at 8:00:00 AM"`

Try changing this date to a date you'd like the counter to run from, save, refresh the widget (due to a bug you might have to restart Ubersicht) and see what happens. Let me know!

**Comment by schaufma** [comment]
hi there!

thanks for your answer … unfortunately it doesn´t help to fix the problem (screenshot)…

i´ve set the date to Sunday, March 13, 2016 at 11:59:00 PM … refresh and restart the widget … same problem …

yes, it could be a general language problem … in the world clock widget i can´t set the time to 24 hours …



thanks 

markus

**Comment by Pe8er** [comment]
> thanks for your answer … unfortunately it doesn´t help to fix the problem (screenshot)…

Screenshot didn't attach, please try again. I will try to debug myself by setting computer's language to German, let's see what happens.

> yes, it could be a general language problem … in the world clock widget i can´t set the time to 24 hours

To do that, you need to open `WorldClock.widget/WorldClock.sh` and for each city you want to change time formatting, replace

`%-l:%M %p`

with

`%H:%M`

**Comment by Pe8er** [comment]
Update: I've added a setting to `WorldClock.widget/WorldClock.sh` which should make your life easier. Look at line 4:

`timeformat=12`

Change 12 to 24 and you're good to go!
